title: Sivasankaran Rajasekaran
logo: assets/Sivasankaran_Rajasekaran.jpg
description: Driving Business Insights as a Certified Microsoft Power BI Data Analyst Associate
#show_downloads:
theme: jekyll-theme-tactile
