title: Sivasankaran Rajasekaran
logo: assets/Sivasankaran_Rajasekaran.jpg
description: Driving Business Insights as a Certified Microsoft Power BI Data Analyst Associate. Connect with me on [LinkedIn](https://www.linkedin.com/in/sivasankaran-rajasekaran/)
#show_downloads:
theme: jekyll-theme-minimal
